pub mod mode;
pub mod state;
pub mod health;
pub mod upgrade;
pub mod rollback;
pub mod cli;
pub mod checksum;
pub mod process;
pub mod spawn;
pub mod ipc_client;
pub mod connection_tracker;
pub mod drain_manager;
pub mod socket_handoff;
pub mod preflight;
pub mod constants;

pub use mode::{UpgradeMode, detect_upgrade_mode, probe_reuseport_support};
pub use state::{UpgradeState, OverseerState, Persistence};
pub use health::{HealthChecker, HealthStatus, EnhancedHealthConfig, EnhancedHealthResult, BaselineComparison, ShadowTrafficResult, retry_with_timeout, wait_for_condition};
pub use upgrade::{Orchestrator, AutoRollbackConfig};
pub use rollback::RollbackManager;
pub use cli::{OverseerArgs, run_overseer_command, UpgradeCommand};
pub use process::{OverseerProcess, OverseerConfig, run_overseer_process};
pub use spawn::{SpawnConfig, ProcessMode, build_spawn_command, spawn_process, spawn_and_log, cleanup_failed_spawns};
pub use ipc_client::{IpcClient, connect_and_expect, send_and_receive, send_message, map_ipc_error};
pub use connection_tracker::{ConnectionTracker, WorkerConnections};
pub use drain_manager::{DrainManager, DrainProtocol};
pub use socket_handoff::{SocketHandoffServer, SocketHandoffClient, DualMasterHandoff, SocketHandoffError};
pub use preflight::{PreflightValidator, PreflightConfig, PreflightResult, PreflightError};
pub use constants::{timeouts, restart, upgrade as upgrade_config, drain};
pub use crate::drain::{DrainStatus, WorkerConnectionInfo, WorkerDrainState};
