pub struct DefaultPatterns;

impl DefaultPatterns {
    pub fn ssti() -> Vec<&'static str> {
        vec![
            "{{",
            "}}",
            "${",
            "#{",
            "{%",
            "%}",
            "{{config",
            "{{self",
            "{{_self",
            "{{_globals",
            "{{request",
            "{{\"",
            "{{'",
            "{{7*7}}",
            "{{7*'7'}}",
            "${7*7}",
            "#{7*7}",
            "{{constructor",
            "{{__class__",
            "{{__mro__",
            "{{__subclasses__",
            "{{__builtins__",
            "{{__import__",
            "{{__globals__",
            "{{__getattribute__",
            "{{ lipsum}}",
            "{{cycler}}",
            "{{joiner}}",
            "{{namespace}}",
            "{{config.items()",
            "{{request.application",
            "{{''.__class__",
            "{{request.environ",
            "{{get_flashed_messages",
            "{{url_for.__globals__",
            "{{lipsum.__globals__",
            "{{cycler.__init__",
            "{{joiner.__init__",
            "{{namespace.__init__",
            "{{range}}",
            "{{dict}}",
            "${{",
            "}}{{",
            "{{tpl",
            "{{template",
            "${T(org.apache.commons",
            "${getClass()",
            "${{}.class",
            "<#assign",
            "<#if",
            "<#else",
            "<#list",
            "<#import",
            "<#include",
            "<#function",
            "${.now}",
            "${.current_template",
            "${.locale}",
            "${.lang}",
            "${.version}",
            "${.output_format",
            "${.output_encoding",
            "<%= ",
            "%>",
            "${applicationScope",
            "${requestScope",
            "${sessionScope",
            "${pageContext",
            "${param.",
            "${header.",
            "${cookie.",
            "{{#if",
            "{{/if",
            "{{#each",
            "{{/each",
            "{{#with",
            "{{/with",
            "{{#unless",
            "{{/unless}",
            "<%=",
            "%>",
            "${system.",
            "${runtime.",
            "${process.",
            "${scripting.",
            "${groovy.",
            "${new ",
            "${new%20",
            "{{system.",
            "{{runtime.",
            "{{process.",
            "Runtime.getRuntime()",
            "ProcessBuilder",
            "java.lang.Runtime",
            "java.lang.Process",
            "javax.script",
            "ScriptEngine",
        ]
    }

    pub fn ssti_high() -> Vec<&'static str> {
        vec![
            ".__class__",
            ".__mro__",
            ".__subclasses__",
            ".__builtins__",
            ".__import__",
            ".__globals__",
            ".__getattribute__",
            ".__init__",
            ".__dict__",
            "getAttribute(",
            "getClass()",
            "forName(",
            "newInstance()",
            "getMethod(",
            "invoke(",
            "java.lang.Class",
            "java.lang.reflect",
            "java.lang.Object",
            "org.apache.commons",
            "org.springframework",
            "freemarker.template",
            "velocity.runtime",
            "org.apache.velocity",
            "org.thymeleaf",
            "com.hubspot",
            "io.pebbletemplates",
            "org.jtwig",
            "org.attoparser",
            "org.jinjava",
            "org.apache.ivy",
            "org.python",
            "org.jruby",
            "javax.el",
            "javax.script",
            "ScriptEngineManager",
            "com.sun.script",
            ".exec(",
            ".start()",
            "ProcessImpl",
            "UNIXProcess",
            "WinNTSystem",
            "/bin/sh",
            "/bin/bash",
            "/bin/zsh",
            "cmd.exe",
            "powershell",
            "bash -c",
            "sh -c",
            "cmd /c",
            "powershell -c",
        ]
    }

    pub fn cmd_injection() -> Vec<&'static str> {
        vec![
            "; cat ",
            "; ls",
            "; id",
            "; whoami",
            "; pwd",
            "; uname",
            "; wget",
            "; curl",
            "; nc ",
            "; netcat",
            "; bash",
            "; sh ",
            "; ksh",
            "; zsh",
            "; echo ",
            "; rm ",
            "; mv ",
            "; cp ",
            "; chmod",
            "; chown",
            "; mkdir",
            "; rmdir",
            "; kill",
            "; ps ",
            "; top",
            "; df ",
            "; du ",
            "; find",
            "; grep",
            "; awk ",
            "; sed ",
            "; head",
            "; tail",
            "; more",
            "; less",
            "; vi ",
            "; vim",
            "; nano",
            "; touch",
            "; python",
            "; perl",
            "; ruby",
            "; php ",
            "; node",
            "; java",
            "| cat ",
            "| ls",
            "| id",
            "| whoami",
            "| pwd",
            "| uname",
            "| wget",
            "| curl",
            "| nc ",
            "| bash",
            "| sh ",
            "| echo ",
            "| head",
            "| tail",
            "| grep",
            "| awk ",
            "| sed ",
            "| sort",
            "| uniq",
            "| wc ",
            "| tee ",
            "| xargs",
            "| base64",
            "| xxd",
            "`cat ",
            "`ls",
            "`id",
            "`whoami",
            "`pwd",
            "`uname",
            "`wget",
            "`curl",
            "$(cat ",
            "$(ls",
            "$(id",
            "$(whoami",
            "$(pwd",
            "$(wget",
            "$(curl",
            "& dir",
            "& type",
            "& net ",
            "& reg ",
            "& wmic",
            "& cmd ",
            "& powershell",
            "&& dir",
            "&& type",
            "&& net ",
            "&& reg ",
            "&& wmic",
            "&& cmd ",
            "&& powershell",
            "%COMSPEC%",
            "%PATH%",
            "%SYSTEMROOT%",
            "%WINDIR%",
            "%TEMP%",
            "%APPDATA%",
            "/etc/passwd",
            "/etc/shadow",
            "/etc/hosts",
            "/etc/group",
            "/proc/self",
            "/proc/version",
            "/var/log",
            "c:\\windows",
            "c:\\winnt",
            "c:\\boot.ini",
            "c:\\windows\\system32",
            "del /",
            "format ",
            "fsutil",
            "schtasks",
            "at ",
            "nslookup",
            "dig ",
            "host ",
            "ping ",
            "traceroute",
            "nmap ",
            "sqlmap",
            "metasploit",
            "msfvenom",
        ]
    }

    pub fn cmd_injection_high() -> Vec<&'static str> {
        vec![
            "|%20",
            ";%20",
            "`%20",
            "$()%20",
            "$(%20",
            "<(%20",
            ">(%20",
            "$IFS",
            "$HOME",
            "$USER",
            "$SHELL",
            "$PATH",
            "$UID",
            "$GID",
            "$BASH",
            "$ZSH",
            "(){",
            ":(){ :|:& };:",
            "/dev/tcp",
            "/dev/udp",
            "/dev/null",
            ">/dev/",
            "2>/dev/",
            "2>&1",
            "&>",
            ";&&",
            "|&&",
            "||",
            "|;",
            ";|",
            "\";",
            "\"|",
            "';",
            "'|",
            "\\`;",
            "\\`|",
            "$('\\x",
            "$(printf",
            "$(echo",
            "$(printf '\\x",
            "xxd -r -p",
            "base64 -d",
            "openssl enc",
            "python -c",
            "perl -e",
            "ruby -e",
            "php -r",
            "node -e",
            "exec ",
            "eval ",
            "system(",
            "passthru(",
            "shell_exec(",
            "popen(",
            "proc_open(",
            "pcntl_exec(",
            "subprocess.",
            "os.system",
            "os.popen",
            "os.spawn",
            "subprocess.call",
            "subprocess.Popen",
            "commands.getoutput",
            "Runtime.exec",
            "ProcessBuilder",
            "Process.start",
        ]
    }

    pub fn xxe() -> Vec<&'static str> {
        vec![
            "<!ENTITY",
            "<!DOCTYPE",
            "SYSTEM \"",
            "SYSTEM '",
            "PUBLIC \"",
            "PUBLIC '",
            "file:///",
            "file://",
            "http://",
            "https://",
            "ftp://",
            "php://",
            "data://",
            "expect://",
            "gopher://",
            "dict://",
            "ldap://",
            "<!ENTITY %",
            "%x",
            "%xxe",
            "%eval",
            "%exfil",
            "%remote",
            "%file",
            "ENTITY xxe",
            "ENTITY % xxe",
            "ENTITY data",
            "ENTITY file",
            "ATTLIST",
            "ELEMENT",
            "<!ATTLIST",
            "<!ELEMENT",
            "xmlns:xi",
            "xi:include",
            "xinclude",
            "XInclude",
            "docType",
            "DocType",
            "DOCTYPE [",
            ".dtd",
            ".ent",
            "<![CDATA[",
            "]]>",
            "encoding=\"",
            "encoding='",
            "standalone=\"yes\"",
            "standalone='yes'",
        ]
    }

    pub fn xxe_high() -> Vec<&'static str> {
        vec![
            "OOB",
            "out-of-band",
            "out of band",
            "parameter entity",
            "external entity",
            "blind xxe",
            "xxe-",
            "xxe_",
            "exfil",
            "exfiltrat",
            "error-based",
            "cdata",
            "CDATA",
            "xmlns:",
            "xsl:include",
            "xsl:import",
            "xslt",
            "transform",
            "stylesheet",
            "<?xml-stylesheet",
            "XSL",
            "xsl:",
            "document(",
            "document('",
            "document(\"",
            "unparsed-entity-uri",
            "unparsed-text",
            "collection(",
            "doc(",
            "doc('",
            "doc(\"",
            "http://169.254",
            "http://127.0.0.1",
            "http://localhost",
            "https://169.254",
            "https://127.0.0.1",
            "https://localhost",
            "file:///etc/",
            "file:///c:/",
            "file:///proc/",
            "jar:",
            "netdoc:",
            "vnd.sun.star.",
        ]
    }

    pub fn jwt() -> Vec<&'static str> {
        vec![
            "\"kid\":\"",
            "\"kid':\"",
            "\"jku\":\"",
            "\"jku':'",
            "\"x5u\":\"",
            "\"x5u':'",
            "\"x5c\":[",
            "\"jwk\":{",
            "\"x5t\":\"",
            "kid=\"http",
            "kid=\"file",
            "kid=\"..",
            "kid=\"/etc",
            "kid=\"/proc",
            "jku=\"http",
            "x5u=\"http",
            "jku=\"file",
            "x5u=\"file",
            "../../../",
            "/etc/passwd",
            "/proc/self",
            "Runtime.getRuntime",
            "ProcessBuilder",
            "exec(",
            "eval(",
            "system(",
            "getClass()",
            "forName(",
            "newInstance()",
            "getMethod(",
        ]
    }

    pub fn path_traversal() -> Vec<&'static str> {
        vec![
            "../",
            "..\\",
            "%2e%2e/",
            "%2e%2e%2f",
            "%252e%252e",
            "..%2f",
            "%2e%2e\\",
            "..%5c",
            "%2e%2e%5c",
            "..%255c",
            "/etc/passwd",
            "/etc/shadow",
            "/etc/hosts",
            "/etc/group",
            "/windows/system32",
            "/win.ini",
            "boot.ini",
            "web.config",
            ".htaccess",
            ".htpasswd",
            "file://",
            "php://input",
            "php://filter",
            "expect://",
            "zip://",
            "phar://",
            "data://",
            "glob://",
            "/proc/self",
            "/proc/version",
            "/proc/cmdline",
        ]
    }

    pub fn path_traversal_high() -> Vec<&'static str> {
        let mut patterns = Self::path_traversal();
        patterns.extend(vec![
            "....//",
            "....\\",
            "..../",
            "..%c0%af",
            "..%c1%9c",
            "..%255c",
            "%c0%ae%c0%ae/",
            "%c0%ae%c0%ae%c0%af",
            "..%00/",
            "..%00\\",
            "..%c0%00/",
            "/var/log",
            "/var/www",
            "/usr/bin",
            "/bin/bash",
            "/bin/sh",
            "cmd.exe",
            "powershell",
            "net user",
            "net localgroup",
        ]);
        patterns
    }

    pub fn rfi() -> Vec<&'static str> {
        vec![
            "=http://",
            "=https://",
            "=ftp://",
            "=php://",
            "=http%3a%2f%2f",
            "=https%3a%2f%2f",
            "php://input",
            "php://filter",
            "data://text/plain",
            "data://text/html",
            "expect://",
            "=//",
            "=\\\\",
            "?file=http://",
            "?file=https://",
            "?page=http://",
            "?page=https://",
            "?include=http://",
            "?path=http://",
            "?url=http://",
            "?link=http://",
            "?src=http://",
            "?dest=http://",
            "?document=http://",
        ]
    }

    pub fn rfi_high() -> Vec<&'static str> {
        let mut patterns = Self::rfi();
        patterns.extend(vec![
            "=http%253a%252f%252f",
            "=https%253a%252f%252f",
            "php%3a%2f%2f",
            "data%3a%2f%2f",
            "expect%3a%2f%2f",
            "?file=ftp://",
            "?page=ftp://",
            "?include=ftp://",
            "?path=ftp://",
            "?url=ftp://",
        ]);
        patterns
    }

    pub fn ssrf() -> Vec<&'static str> {
        vec![
            "localhost",
            "127.0.0.1",
            "0.0.0.0",
            "[::1]",
            "[0:0:0:0:0:0:0:1]",
            "169.254.",
            "metadata.google",
            "metadata.azure",
            "169.254.169.254",
            "10.",
            "172.16.",
            "172.17.",
            "172.18.",
            "172.19.",
            "172.20.",
            "172.21.",
            "172.22.",
            "172.23.",
            "172.24.",
            "172.25.",
            "172.26.",
            "172.27.",
            "172.28.",
            "172.29.",
            "172.30.",
            "172.31.",
            "192.168.",
            "file://",
            "gopher://",
            "dict://",
            "sftp://",
            "tftp://",
            "ldap://",
            "127.1",
            "127.0.1",
            "0177.0.0.1",
            "0x7f.0.0.1",
            "2130706433",
            "0x7f000001",
            "017700000001",
        ]
    }

    pub fn ssrf_high() -> Vec<&'static str> {
        let mut patterns = Self::ssrf();
        patterns.extend(vec![
            "localtest.me",
            "customer1.app-",
            "project.corp.",
            "internal.",
            "intranet.",
            "private.",
            "lab.",
            "staging.",
            "stg.",
            "dev.",
            "test.",
            "uat.",
            "sandbox.",
            "vpn.",
            "ssh.",
            "ftp.",
            "db.",
            "database.",
            "mysql.",
            "postgres.",
            "redis.",
            "mongo.",
            "elastic.",
            "k8s.",
            "kubernetes.",
            "docker.",
            "container.",
            "kube.",
            "consul.",
            "vault.",
            "nomad.",
        ]);
        patterns
    }

    pub fn headers_to_check() -> &'static [&'static str] {
        &[
            "cookie",
            "x-forwarded-for",
            "x-real-ip",
            "x-original-url",
            "x-rewrite-url",
            "x-host",
            "x-forwarded-proto",
            "referer",
            "origin",
        ]
    }

    pub fn ldap_injection() -> Vec<&'static str> {
        vec![
            "*)(&",
            "*)(|(",
            "*(|(objectClass=*",
            "*(objectClass=*",
            "admin)(&(password=*",
            "admin)(!",
            ")(uid=*",
            ")(cn=*",
            ")(ou=*",
            ")(dc=*",
            ")(mail=*",
            ")(sn=*",
            ")(givenName=*",
            ")(telephoneNumber=*",
            ")(userPassword=*",
            ")%29",
            ")%28",
            "%28",
            "%29",
            "%26",
            "%7c",
            "%21",
            ")%20",
            "%20%28",
            "uid=*",
            "cn=*",
            "ou=*",
            "dc=*",
            "dn:",
            "objectClass=*",
            "(objectClass=*",
            "!(objectClass=*",
            "*$",
            "*)",
            "(|(",
            "(&(",
            "(|(uid=*",
            "(|(cn=*",
            "(|(mail=*",
            "(uid=",
            "(cn=",
            "(ou=",
            "(dc=",
            "(sn=",
            "(mail=",
            "(telephoneNumber=",
            "(userPassword=",
        ]
    }

    pub fn ldap_injection_high() -> Vec<&'static str> {
        vec![
            "*%29%28",
            "*%28",
            ")%00",
            ")%00(",
            "null",
            "%00",
            "%00(",
            "*%00*",
            "*/",
            "/*",
            "/**/",
            "admin",
            "root",
            "administrator",
            "password",
            "passwd",
            "secret",
            "confidential",
            "*)(uid=*",
            "*)(cn=*",
            "*)(ou=*",
            "*)(dc=*",
            "*)(member=*",
            "*)(memberOf=*",
            "*)(owner=*",
            "*)(group=*",
            "*)(description=*",
            "*)(jpegPhoto=*",
            "*)(userCertificate=*",
            "*)(mozillaPersonUid=*",
            "(memberOf=CN=*",
            "(memberOf=DN=*",
            "(member:1.2.840.113556.1.4.804:=*",
            "(member;range=0-*",
            "(distinguishedName=*",
            "(name=*",
            "(simpleCommonName=*",
            "(simpleDisplayName=*",
            "(displayName=*",
            "(relativeDomainName=*",
            "(domainComponent=*",
            "(stateOrProvinceName=*",
            "(streetAddress=*",
            "(postalCode=*",
            "(c=*",
            "(co=*",
            "(countryName=*",
            "(organizationName=*",
            "(organizationalUnitName=*",
            "(title=*",
            "(description=*",
            "(facsimileTelephoneNumber=*",
            "(l=*",
            "(st=*",
            "(postalAddress=*",
            "(homePhone=*",
            "(mobile=*",
            "(pager=*",
            "(initials=*",
            "(x500UniqueIdentifier=*",
            "(inline",
            "x-order",
        ]
    }

    pub fn xpath_injection() -> Vec<&'static str> {
        vec![
            "']",
            "']=",
            "']/*",
            "']/child::",
            "']/parent::",
            "']/ancestor::",
            "']/descendant::",
            "']/following::",
            "']/preceding::",
            "']/self::",
            "']and'1'='1",
            "']or'1'='1",
            "']and false()",
            "']or true()",
            "']=|",
            "']=1",
            "substring(",
            "contains(",
            "normalize-space",
            "string-length",
            "concat(",
            "substring-before(",
            "substring-after(",
            "translate(",
            "boolean(",
            "ceiling(",
            "floor(",
            "round(",
            "sum(",
            "not(",
            "true()",
            "false()",
            "comment()",
            "node()",
            "text()",
            "ancestor::",
            "ancestor-or-self::",
            "attribute::",
            "child::",
            "descendant::",
            "descendant-or-self::",
            "following::",
            "following-sibling::",
            "parent::",
            "preceding::",
            "preceding-sibling::",
            "self::",
            "/text()",
            "/comment()",
            "/processing-instruction(",
            "='",
            "='*",
            "=']",
            "=substring(",
            "=contains(",
            "count(",
            "name(",
            "local-name(",
            "namespace-uri(",
            "position()",
        ]
    }

    pub fn xpath_injection_high() -> Vec<&'static str> {
        vec![
            "']%20and%20'1'='1",
            "']%20or%20'1'='1",
            "']and'1'='1",
            "']or'1'='1",
            "']and false()",
            "']or true()",
            "'])|",
            "'])|//",
            "'])|/descendant::",
            "'])|/child::",
            "'%20and%20'1'='1",
            "'%20or%20'1'='1",
            "and%20'1'='1",
            "or%20'1'='1",
            "'])|(@*",
            "'])|*",
            "']-1=1",
            "']1=1",
            "']=1=1",
            "substring//",
            "contains//",
            "admin' or '1'='1",
            "admin' or '1'='1' --",
            "admin' or '1'='1' #",
            "admin' or '1'='1'/*",
            "admin' or '1'='1' or 'a'='a",
            "admin' and '1'='1",
            "admin' and '1'='2",
            "' or ''='",
            "' or 1=1--",
            "' or 'a'='a",
            "' or 1=1#",
            "'])-1=1",
            "'])-1]-1",
            "' and 1=1 and ''='",
            "']//*[",
            "//*[contains(",
            "//*[starts-with(",
            "//*[contains(@",
            "//*[contains(text()",
        ]
    }

    pub fn open_redirect() -> Vec<&'static str> {
        vec![
            "://",
            "http://",
            "https://",
            "///",
            "//\\",
            "\\\\",
            "redirect=",
            "url=",
            "link=",
            "goto=",
            "next=",
            "data=",
            "reference=",
            "site=",
            "html=",
            "val=",
            "validate=",
            "domain=",
            "callback=",
            "return=",
            "page=",
            "feed=",
            "host=",
            "port=",
            "path=",
            "continue=",
            "uri=",
            "dest=",
            "destination=",
            "redir=",
            "rurl=",
            "service=",
            "transfer=",
            "spage=",
            "qpa=",
            "cpage=",
            "query=",
            "token=",
            "email=",
            "mail=",
            "subject=",
            "template=",
            "view=",
            "dir=",
            "show=",
            "pg=",
            "p=",
            "method=",
            "do=",
            "func=",
            "call=",
            "file=",
            "document_id=",
            "document_id=",
            "folder=",
            "pg=",
            "style=",
            "doc=",
            "img_url=",
            "return_path=",
            "success_url=",
            "error_url=",
            "target=",
            "out=",
            "viewpage=",
            "open=",
            "top=",
            "frame=",
            "display=",
            "src=",
            "source=",
            "mode=",
            "name=",
            "to=",
            "rest_url=",
            "continue_url=",
            "u=",
            "urlfrom=",
            "urlsrc=",
            "redir_url=",
            "redirect_uri=",
            "redirect_url=",
            "oauth_callback=",
            "callback_url=",
            "return_to=",
            "return_url=",
            "from_url=",
            "serve=",
            "proxy=",
            "bigimg=",
            "url_link=",
            "linkurl=",
            "origin=",
            "originUrl=",
            "sourceUrl=",
            "contentUrl=",
            "shareUrl=",
        ]
    }

    pub fn open_redirect_high() -> Vec<&'static str> {
        vec![
            "%2F%2F",
            "%2F%2F%2F",
            "%5C%5C",
            "%5C%5C%5C",
            "%2e%2e",
            "%2e%2e%2f",
            "%2e%2e%5c",
            "..%2f",
            "..%5c",
            ".%2e",
            ".%5c",
            "%252e",
            "%252e%252e",
            "..%252f",
            "javascript:",
            "javascript%3a",
            "vbscript:",
            "vbscript%3a",
            "data:text/html",
            "data:text/javascript",
            "data:",
            "file://",
            "ftp://",
            "smb://",
            "telnet:",
            "ssh:",
            "rdp://",
            "mstsc://",
            "xcc://",
            "xsi://",
            "xcr://",
            "xsi:",
            "xcr:",
            "gopher://",
            "dict://",
            "sftp://",
            "tftp://",
            "ldap://",
            "imap://",
            "pop://",
            "smtp://",
            "news://",
            "sip:",
            "sips:",
            "tel:",
            "skype:",
            "spotify:",
            "steam:",
            "magnet:",
            "spotify:",
            "slack:",
            "zoom:",
            "mattermost:",
            "discord:",
            "teams:",
            "facetime:",
            "xmpp:",
            "irc:",
            "ircs:",
            "matrix:",
            "sip:",
            "sips:",
            "msnim:",
            "chat:",
            "whatsapp:",
            "tg:",
            "telegram:",
            "intent://",
            "market://",
            "app://",
            "mobile://",
            "chrome://",
            "edge://",
            "about://",
            "chrome-extension://",
            "moz-extension://",
        ]
    }
}
