use crate::admin::handlers::{
    alerting, config, icmp, logs, mesh_admin, probes, rule_feed, sites, stats, system, tcp_udp,
    theme, threat_level, upstreams,
};
use utoipa::OpenApi;

#[derive(OpenApi, Default)]
#[openapi(
    info(
        title = "MaluWAF Admin API",
        description = "REST API for MaluWAF administration and monitoring",
        version = "0.1.0"
    ),
    servers(
        (url = "http://localhost:8081/api", description = "Local admin API")
    ),
    components(
        schemas(
            stats::SystemStats,
            stats::SiteStats,
            stats::MetricsHistoryParams,
            stats::AttackStats,
            stats::CacheStats,
            system::MasterStatusResponse,
            system::MasterMetricsResponse,
            system::SystemInfoResponse,
            system::WorkerStatusResponse,
            system::OverseerStatusResponse,
            upstreams::UpstreamStatus,
            upstreams::SiteUpstreams,
            upstreams::HealthCheckResponse,
            logs::LogsQuery,
            logs::LogEntry,
            logs::LogsResponse,
            logs::ErrorPageResponse,
            tcp_udp::TcpUdpListener,
            tcp_udp::ListListenersResponse,
            tcp_udp::ProtocolInfo,
            theme::ThemeResponse,
            theme::ThemeColorsResponse,
            theme::DarkColors,
            theme::LightColors,
            theme::ThemePresetInfo,
            alerting::AlertConfigResponse,
            alerting::TestAlertResponse,
            rule_feed::RuleFeedStatusResponse,
            rule_feed::RuleFeedCheckResponse,
            rule_feed::RuleFeedApplyResponse,
            probes::ProbeResponse,
            probes::ProbeEventResponse,
            probes::ProbeStatsResponse,
            probes::ProbeEndpointStatsResponse,
            probes::BlockProbesRequest,
            probes::SuspiciousWordRecordResponse,
            probes::SuspiciousWordListResponse,
            probes::SuspiciousWordStatsResponse,
            probes::SuspiciousWordCountResponse,
            probes::UpstreamErrorRecordResponse,
            probes::UpstreamErrorListResponse,
            probes::UpstreamErrorStatsResponse,
            probes::UpstreamErrorEndpointCountResponse,
            icmp::IcmpStatusResponse,
            icmp::IcmpStats,
            icmp::IcmpConfigResponse,
            icmp::UpdateIcmpConfigRequest,
            icmp::IcmpEnableResponse,
            icmp::IcmpBackend,
            icmp::IcmpBackendsResponse,
            mesh_admin::MeshNodeInfo,
            mesh_admin::MeshNodeListResponse,
            mesh_admin::BanIpRequest,
            mesh_admin::BanMeshIdRequest,
            mesh_admin::UnbanRequest,
            mesh_admin::BanRecord,
            mesh_admin::BanListResponse,
            mesh_admin::MeshAdminStatusResponse,
            mesh_admin::SignatureFailureReport,
            mesh_admin::SignatureFailureResponse,
            mesh_admin::AuditReportRequest,
            mesh_admin::AuditReportResponseDto,
            sites::SiteInfo,
            sites::SiteDetail,
            sites::CreateSiteRequest,
            sites::UpdateSiteRequest,
            sites::SiteThemeResponse,
            sites::UpdateSiteThemeRequest,
            threat_level::ThreatLevelStatusResponse,
            threat_level::ThreatLevelHistoryResponse,
            threat_level::HistorySample,
            threat_level::BaselineStatsResponse,
            threat_level::BaselineMetric,
            threat_level::SetLevelRequest,
            threat_level::BackupResponse,
            threat_level::BackupsListResponse,
            threat_level::DeleteBackupQuery,
            config::ConfigFieldSchema,
            crate::admin::handlers::common::StatusResponse,
        )
    ),
    paths(
        stats::get_summary,
        stats::get_sites_stats,
        stats::get_metrics_history,
        stats::get_attack_stats,
        stats::get_cache_stats,
        stats::get_bandwidth,
        system::get_master_status,
        system::get_system_info,
        system::get_workers,
        system::restart_worker,
        system::get_overseer,
        upstreams::list_upstreams,
        upstreams::get_site_upstreams,
        upstreams::trigger_health_check,
        logs::get_logs,
        logs::list_error_pages,
        logs::get_error_page,
        logs::update_error_page,
        config::get_main_config,
        config::get_config_schema,
        tcp_udp::list_listeners,
        tcp_udp::create_listener,
        tcp_udp::delete_listener,
        tcp_udp::list_protocols,
        theme::get_theme,
        theme::update_theme,
        theme::get_theme_css,
        theme::get_theme_presets,
        alerting::get_alert_config,
        alerting::update_alert_config,
        alerting::test_webhook,
        rule_feed::get_status,
        rule_feed::check_for_updates,
        rule_feed::apply_pending,
        rule_feed::discard_pending,
        probes::list_probes,
        probes::get_probe,
        probes::get_probe_stats,
        probes::delete_probe,
        probes::block_probes,
        probes::list_suspicious_words,
        probes::get_suspicious_word_stats,
        probes::delete_suspicious_word,
        probes::list_upstream_errors,
        probes::get_upstream_error_stats,
        probes::delete_upstream_error,
        icmp::get_status,
        icmp::get_config,
        icmp::update_config,
        icmp::enable,
        icmp::disable,
        icmp::list_backends,
        mesh_admin::get_mesh_status,
        mesh_admin::list_mesh_nodes,
        mesh_admin::get_mesh_node,
        mesh_admin::ban_ip,
        mesh_admin::ban_mesh_id,
        mesh_admin::unban,
        mesh_admin::list_bans,
        mesh_admin::submit_audit_report,
        mesh_admin::report_signature_failure,
        sites::list_sites,
        sites::get_site,
        sites::create_site,
        sites::delete_site,
        sites::update_site,
        sites::get_site_theme,
        sites::update_site_theme,
        threat_level::get_status,
        threat_level::get_history,
        threat_level::get_baseline,
        threat_level::reset_baseline,
        threat_level::set_level,
        threat_level::set_auto,
        threat_level::create_backup,
        threat_level::list_backups,
        threat_level::delete_backup,
        threat_level::prune_history,
        threat_level::get_history_stats,
    ),
    tags(
        (name = "Health", description = "Health check endpoints"),
        (name = "Stats", description = "Statistics and metrics endpoints"),
        (name = "System", description = "System status and management"),
        (name = "Sites", description = "Site configuration endpoints"),
        (name = "Upstreams", description = "Upstream management endpoints"),
        (name = "Logs", description = "Log and error page endpoints"),
        (name = "Config", description = "Configuration endpoints"),
        (name = "TCP/UDP", description = "TCP/UDP listener endpoints"),
        (name = "Probes", description = "Probe tracking endpoints"),
        (name = "Threat Level", description = "Threat level management"),
        (name = "Alerting", description = "Alert configuration endpoints"),
        (name = "Rules", description = "Rule feed management"),
        (name = "ICMP", description = "ICMP filter management"),
        (name = "Mesh", description = "Mesh network management"),
        (name = "Theme", description = "Theme customization endpoints"),
    )
)]
pub struct ApiDoc;

impl From<ApiDoc> for utoipa::openapi::OpenApi {
    fn from(_doc: ApiDoc) -> Self {
        ApiDoc::openapi()
    }
}
